### PR TITLE
Fix for bba to make it portable

### LINKED ISSUE #366: basename not declared in bba/main.c
When I try to build for ice40 I get the following error
```
bba/main.cc:450:49: error: use of undeclared identifier
      'basename'
        fprintf(fileOut, "#embed_str \"%s\"\n", basename(bin_basename_buf));

```
I "fixed" the issue by including libgen.h in bba/main.c

### PR DESCRIPTION
**Pull request by mmicko**
We anyway use filesystem and system library from Boost and this makes it portable on macOS and Windows, fixes #366

### CODE REVIEW

File: bba/main.cc [hunk 1]
```diff
@@ -446,8 +447,7 @@ int main(int argc, char **argv)
             fprintf(fileOut, "%s\n", s.c_str());
 
         fprintf(fileOut, "const char %s[%d] =\n", streams[0].name.c_str(), int(data.size()) + 1);
-        char *bin_basename_buf = strdup(files.at(2).c_str());
-        fprintf(fileOut, "#embed_str \"%s\"\n", basename(bin_basename_buf));
+        fprintf(fileOut, "#embed_str \"%s\"\n",boost::filesystem::basename(files.at(2)).c_str());
```
Comment (daveshah1) [inline bba/main.cc]: looks like you didn't run clangformat? missing space after ,

Comment (mmicko) [reply bba/main.cc]: ah, missed that. thanks
